name: Bump version tags on release

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update manifest.json version
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#"v"}
          jq --arg version "$VERSION" '.version = $version' custom_components/actronair_neo/manifest.json > manifest.tmp
          mv manifest.tmp custom_components/actronair_neo/manifest.json
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add custom_components/actronair_neo/manifest.json
          git commit -m "Bump version to $TAG"
      - name: Push changes
        run: |
          git push origin HEAD:main
